project:
  type: website

website:
  title: "pblog"
  navbar:
    right:
      - href: https://pws3141.github.io
        text: Home
        icon: house
      - about.qmd
      - icon: github
        href: https://github.com/pws3141/blog
format:
  html:
    theme: flatly
    css: styles.css
    code-fold: show
    grid:
      margin-width: 350px
    df-print: paged
    toc: true
    toc-location: left
    code-annotations: hover
execute:
  echo: true
  freeze: false
bibliography: ref.bib
reference-location: margin
citation-location: margin
fig-cap-location: margin
lst-cap-location: margin
tbl-cap-location: margin
link-citations: true
citation: true
google-scholar: true
