project:
  type: website

website:
  title: "pblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pws3141/pblog
format:
  html:
    theme: flatly
    css: styles.css
    code-fold: show
    grid:
      margin-width: 350px
    df-print: paged # pages html tables: https://quarto.org/docs/computations/r.html#data-frames
execute:
  echo: true
bibliography: ref.bib
reference-location: margin
citation-location: margin
fig-cap-location: margin
tbl-cap-location: margin
link-citations: true
